name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile main.py --name k8s-sp

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: dist/k8s-sp
          body: |
            ### What's Changed
            - [template]
            #### New Features
            - [template] 
            #### Bug Fixes
            - [template]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}